version: '2'

services:

  great-big-angular2-example:
    build:
      context: .
      dockerfile: ./.docker/great-big-angular2-example.development.dockerfile
    command: npm start
    container_name: great-big-angular2-example-start
    image: great-big-angular2-example
    networks:
      - dev-network
    ports:
      - '4200:4200'

networks:
  dev-network:
    driver: bridge