version: '2'

services:

  angular-seed:
    build:
      context: .
      dockerfile: ./.docker/great-big-angular2-example.production.dockerfile
    command: ng build --prod
    container_name: great-big-angular2-example-build-prod
    image: great-big-angular2-example
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/great-big-angular2-example/dist

  great-big-angular2-example-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/great-big-angular2-example.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: great-big-angular2-example-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '4200:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/great-big-angular2-example.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge